#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Dec  2 14:10:14 2018

@author: atatarian
"""

#Manipulating the original data file in Unix before graphing:
#cat RNAfileMatches3.csv | sed ’s/ /,/g’ | cut -d , -f 1,3,4 > RNAfileMatches4.csv

import numpy as np
import pandas
from plotnine import *
exp=pandas.read_csv("RNAfileMatches4.csv",sep=",",header=0,usecols=['Matches', 'RNA', 'Protein'])

print exp

print ggplot(exp, aes(x="Protein", y="Matches",fill="RNA"))+geom_bar(stat='identity',position='dodge')+theme(axis_text_x=element_text(rotation=35,ha='right'))