#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sun Dec  2 14:10:14 2018

@author: atatarian
"""

import matplotlib
import numpy
import pandas
from plotnine import *
exp=pandas.read_csv("RNAfileMatches2.csv",sep=",",header=1,usecols=['Matches', 'RNA', 'Sequence'])

print exp

#print (exp['RNA'] == "Control1protein.fasta" & "Control2protein.fasta")



#a=ggplot(exp,aes(x="Protein",y="Expression Level"))+geom_point(color="blue",shape=4,size=3)

#print a+theme_classic()+xlab("displacment (l)")+ylab("Expression Level")

#color for normal 
#color for obese

#in the csv file, we need to distinguish which normal/obese correlates to which protein.